In [1]:
import numpy as np

In [2]:
np.random.seed(42)
tri = np.tril(np.floor(np.random.random([8,8])*10))
tri

array([[ 3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 6.,  7.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  5.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 4.,  7.,  1.,  5.,  0.,  0.,  0.,  0.],
       [ 0.,  9.,  9.,  8.,  3.,  0.,  0.,  0.],
       [ 1.,  4.,  0.,  9.,  2.,  6.,  0.,  0.],
       [ 5.,  1.,  9.,  7.,  9.,  8.,  5.,  0.],
       [ 0.,  1.,  0.,  3.,  3.,  2.,  8.,  3.]])

In [3]:
nump_inv = np.tril(np.linalg.inv(tri))

In [4]:
np.set_printoptions(precision=2)
nump_inv

array([[ 0.33,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [-0.29,  0.14,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.11, -0.18,  0.25,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.11, -0.16, -0.05,  0.2 ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.24,  0.55, -0.62, -0.53,  0.33,  0.  ,  0.  ,  0.  ],
       [-0.11, -0.03,  0.28, -0.12, -0.11,  0.17,  0.  ,  0.  ],
       [-0.87, -0.41,  0.28,  0.88, -0.42, -0.27,  0.2 ,  0.  ],
       [ 2.15,  0.68, -0.27, -1.92,  0.87,  0.6 , -0.53,  0.33]])

In [5]:
csanky_inv = tri.copy()

In [6]:
for i in range(8):
    csanky_inv[i,i] = 1.0/csanky_inv[i,i]
csanky_inv

array([[ 0.33,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 6.  ,  0.14,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 3.  ,  5.  ,  0.25,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 4.  ,  7.  ,  1.  ,  0.2 ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  9.  ,  9.  ,  8.  ,  0.33,  0.  ,  0.  ,  0.  ],
       [ 1.  ,  4.  ,  0.  ,  9.  ,  2.  ,  0.17,  0.  ,  0.  ],
       [ 5.  ,  1.  ,  9.  ,  7.  ,  9.  ,  8.  ,  0.2 ,  0.  ],
       [ 0.  ,  1.  ,  0.  ,  3.  ,  3.  ,  2.  ,  8.  ,  0.33]])

In [7]:
for i in range(0,8,2):
    B_inv = csanky_inv[i,i]
    C = csanky_inv[i+1,i]
    D_inv = csanky_inv[i+1,i+1]
    csanky_inv[i+1,i] = -D_inv*C*B_inv
csanky_inv

array([[ 0.33,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [-0.29,  0.14,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 3.  ,  5.  ,  0.25,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 4.  ,  7.  , -0.05,  0.2 ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  9.  ,  9.  ,  8.  ,  0.33,  0.  ,  0.  ,  0.  ],
       [ 1.  ,  4.  ,  0.  ,  9.  , -0.11,  0.17,  0.  ,  0.  ],
       [ 5.  ,  1.  ,  9.  ,  7.  ,  9.  ,  8.  ,  0.2 ,  0.  ],
       [ 0.  ,  1.  ,  0.  ,  3.  ,  3.  ,  2.  , -0.53,  0.33]])

In [8]:
for i in range(0,8,4):
    B_inv = csanky_inv[i:i+2,i:i+2]
    D_inv = csanky_inv[i+2:i+4,i+2:i+4]
    C = csanky_inv[i+2:i+4,i:i+2]
    C[:,:] = -D_inv.dot(C).dot(B_inv)

In [9]:
csanky_inv

array([[ 0.33,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [-0.29,  0.14,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.11, -0.18,  0.25,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.11, -0.16, -0.05,  0.2 ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  9.  ,  9.  ,  8.  ,  0.33,  0.  ,  0.  ,  0.  ],
       [ 1.  ,  4.  ,  0.  ,  9.  , -0.11,  0.17,  0.  ,  0.  ],
       [ 5.  ,  1.  ,  9.  ,  7.  , -0.42, -0.27,  0.2 ,  0.  ],
       [ 0.  ,  1.  ,  0.  ,  3.  ,  0.87,  0.6 , -0.53,  0.33]])

In [10]:
B_inv = csanky_inv[0:4,0:4]
D_inv = csanky_inv[4:8,4:8]
C = csanky_inv[4:8,0:4]
C[:,:] = -D_inv.dot(C).dot(B_inv)

In [11]:
csanky_inv

array([[ 0.33,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [-0.29,  0.14,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.11, -0.18,  0.25,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.11, -0.16, -0.05,  0.2 ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.24,  0.55, -0.62, -0.53,  0.33,  0.  ,  0.  ,  0.  ],
       [-0.11, -0.03,  0.28, -0.12, -0.11,  0.17,  0.  ,  0.  ],
       [-0.87, -0.41,  0.28,  0.88, -0.42, -0.27,  0.2 ,  0.  ],
       [ 2.15,  0.68, -0.27, -1.92,  0.87,  0.6 , -0.53,  0.33]])

In [12]:
np.abs(csanky_inv-nump_inv).max()

1.7763568394002505e-15

In [13]:
def tri_inv(A,n):
    for j in range(n):
        A[j,j] = 1.0/A[j,j]
    for i in range(int(np.log2(n))):
        scale = 2**i
        for j in range(0,n,2*scale):
            B_inv = A[j:j+scale,j:j+scale]
            D_inv = A[j+scale:j+2*scale,j+scale:j+2*scale]
            C = A[j+scale:j+2*scale,j:j+scale]
            C[:,:] = -D_inv.dot(C).dot(B_inv)

In [14]:
A = tri.copy()
tri_inv(A,8)
A

array([[ 0.33,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [-0.29,  0.14,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.11, -0.18,  0.25,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.11, -0.16, -0.05,  0.2 ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.24,  0.55, -0.62, -0.53,  0.33,  0.  ,  0.  ,  0.  ],
       [-0.11, -0.03,  0.28, -0.12, -0.11,  0.17,  0.  ,  0.  ],
       [-0.87, -0.41,  0.28,  0.88, -0.42, -0.27,  0.2 ,  0.  ],
       [ 2.15,  0.68, -0.27, -1.92,  0.87,  0.6 , -0.53,  0.33]])

In [61]:
np.random.seed(42)
big_tri = np.tril(np.random.random([1000,1000])*10)

In [62]:
np.linalg.cond(big_tri)

3.6216398895420613e+19

In [64]:
big_tri

array([[ 3.75,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 1.85,  5.42,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 2.62,  2.47,  9.06, ...,  0.  ,  0.  ,  0.  ],
       ..., 
       [ 0.85,  0.92,  6.94, ...,  9.3 ,  0.  ,  0.  ],
       [ 7.6 ,  9.64,  0.05, ...,  3.35,  4.  ,  0.  ],
       [ 1.14,  1.6 ,  8.26, ...,  4.18,  4.29,  9.29]])

In [74]:
big_tri = big_tri - np.diag(big_tri.diagonal()) + np.diag(np.ones(1000))

In [75]:
np.linalg.cond(big_tri)

7.0995532433017823e+19

See the article [CONDITION NUMBERS OF RANDOM TRIANGULAR MATRICES](http://www.math.lsa.umich.edu/~divakar/ViswanathTrefethen1998.pdf) by Viswanath and Trefethen for an explaination of why this procedure goes horrible wrong and why lower triangular matrices $L$ from and $LU$ factorization of a random matrix are much more stable.

In [78]:
from scipy.linalg import lu
np.random.seed(42)
A = np.random.random([1000,1000])*10
P,L,U = lu(A)

In [80]:
np.linalg.cond(L)

2288.4490589552397

In [81]:
%%timeit
np.linalg.inv(L)

10 loops, best of 3: 32.8 ms per loop


In [82]:
%%timeit
L_inv = L.copy()
tri_inv(L,1000)

100 loops, best of 3: 12.4 ms per loop


In [83]:
np_inv = np.linalg.inv(big_tri)

In [84]:
my_inv = big_tri.copy()
tri_inv(my_inv,1000)

In [85]:
print('Average np error:',np.abs(np_inv.dot(big_tri)-np.eye(1000)).mean())
print('Max np error:',np.abs(np_inv.dot(big_tri)-np.eye(1000)).max())

Average np error: 2.57154046006
Max np error: 784.88018381


In [86]:
print('Average csanky error:',np.abs(my_inv.dot(big_tri)-np.eye(1000)).mean())
print('Max csanky error:',np.abs(my_inv.dot(big_tri)-np.eye(1000)).max())

Average csanky error: 8.80645483785e+266
Max csanky error: 2.04924928725e+270


In [26]:
big_tri = np.tril(np.random.random([10000,10000])*10)

In [27]:
%%timeit
np.linalg.inv(big_tri)

1 loop, best of 3: 29.1 s per loop


In [29]:
%%timeit
big_tri_inv = big_tri.copy()
tri_inv(big_tri_inv,10000)

1 loop, best of 3: 3.84 s per loop


In [ ]:
np.linalg.inv(big_tri)

In [17]:
np.abs(A.dot(tri)-np.eye(8)).max()

1.7763568394002505e-15

In [19]:
np.abs(np.linalg.inv(tri).dot(tri)-np.eye(8)).max()

5.3290705182007514e-15

In [20]:
np.abs(A.dot(tri)-np.eye(8)).mean()

1.3183898417423734e-16

In [21]:
np.abs(np.linalg.inv(tri).dot(tri)-np.eye(8)).mean()

6.0817115874132871e-16

In [ ]:
np.tril(np.random.random([1000,1000])*10)

In [96]:
%load_ext cython

In [104]:
%%cython


CompileError: command 'gcc' failed with exit status 1

In [1]:
import pyopencl as cl
import pyopencl.array

In [2]:
%load_ext pyopencl.ipython_ext

In [3]:
ctx = cl.create_some_context(interactive=True)

In [4]:
queue = cl.CommandQueue(ctx)

In [6]:
%%cl_kernel -o "-cl-fast-relaxed-math"

__kernel void sum_vector(__global const float *a,__global const float *b, __global float *c)
{
    int gid = get_global_id(0);
    c[gid] = a[gid] + b[gid];
}

In [9]:
n = 10000

a = cl.array.empty(queue, n, dtype=np.float32)
a.fill(15)

b_host = np.random.randn(n).astype(np.float32)
b = cl.array.to_device(queue,b_host)


c = cl.array.empty_like(a)

In [11]:
sum_vector(queue, (n,), None, a.data, b.data, c.data)

In [ ]:
c